spring:
  application:
    name: auth

  datasource:
    url: jdbc:mysql://localhost:3306/birthday?&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update